# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0002_auto_20160706_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text_ru',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0440\u0443\u0441\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ky',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435'),
        ),
    ]
