# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import simple_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0003_auto_20160706_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.TextField(verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441 \u043d\u0430 \u0440\u0443\u0441\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('question_ky', models.TextField(verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441 \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('answer_ru', models.TextField(verbose_name='\u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u0440\u0443\u0441\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('answer_ky', models.TextField(verbose_name='\u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0432\u043e\u043f\u0440\u043e\u0441 \u0438 \u043e\u0442\u0432\u0435\u0442',
            },
        ),
        migrations.CreateModel(
            name='Hotline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=1000, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0433\u043e\u0440\u044f\u0447\u0435\u0439 \u043b\u0438\u043d\u0438\u0438 \u043d\u0430 \u0440\u0443\u0441\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('text_ru', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u0430 \u0440\u0443\u0441\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('title_ky', models.CharField(max_length=1000, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0433\u043e\u0440\u044f\u0447\u0435\u0439 \u043b\u0438\u043d\u0438\u0438 \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('text_ky', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('phone_number', models.CharField(max_length=100, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u0433\u043e\u0440\u044f\u0447\u0443\u044e \u043b\u0438\u043d\u0438\u044e',
                'verbose_name_plural': '\u0413\u043e\u0440\u044f\u0447\u0438\u0435 \u043b\u0438\u043d\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='RulesOfIncoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=simple_app.models.image_upload_to, verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430')),
                ('title_ru', models.CharField(max_length=1000, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043d\u0430 \u0440\u0443\u0441\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('title_ky', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('text_ru', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0440\u0443\u0441\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('text_ky', models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u0430\u0432\u0438\u043b\u043e \u043f\u0440\u0435\u0431\u044b\u0432\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u041f\u0440\u0430\u0432\u0438\u043b\u0430 \u043f\u0440\u0435\u0431\u044b\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='RulesOfMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=simple_app.models.image_upload_to, verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430')),
                ('title_ru', models.CharField(max_length=1000, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043d\u0430 \u0440\u0443\u0441\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('title_ky', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('text_ru', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0440\u0443\u0441\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('text_ky', models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u0430\u0432\u0438\u043b\u043e \u0432\u044b\u0435\u0437\u0434\u0430',
                'verbose_name_plural': '\u041f\u0440\u0430\u0432\u0438\u043b\u0430 \u0432\u044b\u0435\u0437\u0434\u0430',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ky',
        ),
        migrations.AlterField(
            model_name='news',
            name='text_ru',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=1000, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
