# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0004_auto_20160707_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': '\u0432\u043e\u043f\u0440\u043e\u0441 \u0438 \u043e\u0442\u0432\u0435\u0442', 'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u0438 \u043e\u0442\u0432\u0435\u0442\u044b'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ky',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ky',
            field=models.TextField(blank=True, null=True, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441 \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435'),
        ),
    ]
