# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0005_auto_20160707_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesOfMigrationKy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ky', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
                ('text_ky', models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435')),
            ],
        ),
        migrations.RemoveField(
            model_name='rulesofmigration',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='rulesofmigration',
            name='title_ky',
        ),
        migrations.AddField(
            model_name='rulesofmigrationky',
            name='translit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simple_app.RulesOfMigration'),
        ),
    ]
