# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0006_auto_20160707_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ky', models.TextField(blank=True, null=True, verbose_name='\u0421\u0443\u0440\u043e\u043e')),
                ('answer_ky', models.TextField(blank=True, null=True, verbose_name='\u0416\u043e\u043e\u043f')),
            ],
            options={
                'verbose_name': '\u0441\u0443\u0440\u043e\u043e \u0436\u0430\u043d\u0430 \u0436\u043e\u043e\u043f',
                'verbose_name_plural': '\u0441\u0443\u0440\u043e\u043e \u0436\u0430\u043d\u0430 \u0436\u043e\u043e\u043f',
            },
        ),
        migrations.CreateModel(
            name='HotlineKy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ky', models.CharField(max_length=1000, verbose_name='Hotline')),
                ('text_ky', models.TextField(verbose_name='\u0411\u0430\u044f\u043d\u0434\u043e\u043e')),
            ],
            options={
                'verbose_name_plural': 'hotline',
            },
        ),
        migrations.CreateModel(
            name='RulesOfIncomingKy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ky', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u0410\u0442\u0430\u043b\u044b\u0448')),
                ('text_ky', models.TextField(blank=True, null=True, verbose_name='\u0411\u0430\u044f\u043d\u0434\u043e\u043e')),
            ],
            options={
                'verbose_name': '\u041a\u0435\u043b\u04af\u04af \u044d\u0440\u0435\u0436\u0435',
                'verbose_name_plural': '\u041a\u0435\u043b\u04af\u04af \u044d\u0440\u0435\u0436\u0435',
            },
        ),
        migrations.AlterModelOptions(
            name='rulesofmigrationky',
            options={'verbose_name': '\u0421\u044b\u0440\u0442\u043a\u0430 \u0447\u044b\u0433\u0443\u0443 \u044d\u0440\u0435\u0436\u0435', 'verbose_name_plural': '\u0421\u044b\u0440\u0442\u043a\u0430 \u0447\u044b\u0433\u0443\u0443 \u044d\u0440\u0435\u0436\u0435'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_ky',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ky',
        ),
        migrations.RemoveField(
            model_name='hotline',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='hotline',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='rulesofincoming',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='rulesofincoming',
            name='title_ky',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(verbose_name='\u041e\u0442\u0432\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='text_ru',
            field=models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='title_ru',
            field=models.CharField(max_length=1000, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0433\u043e\u0440\u044f\u0447\u0435\u0439 \u043b\u0438\u043d\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='rulesofincoming',
            name='text_ru',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='rulesofincoming',
            name='title_ru',
            field=models.CharField(max_length=1000, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='rulesofmigration',
            name='text_ru',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='rulesofmigration',
            name='title_ru',
            field=models.CharField(max_length=1000, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='rulesofmigrationky',
            name='text_ky',
            field=models.TextField(blank=True, null=True, verbose_name='\u0411\u0430\u044f\u043d\u0434\u043e\u043e'),
        ),
        migrations.AlterField(
            model_name='rulesofmigrationky',
            name='title_ky',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u0410\u0442\u0430\u043b\u044b\u0448'),
        ),
        migrations.AddField(
            model_name='rulesofincomingky',
            name='translit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simple_app.RulesOfIncoming'),
        ),
        migrations.AddField(
            model_name='faqky',
            name='translit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simple_app.FAQ'),
        ),
    ]
