# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0007_auto_20160707_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotlineky',
            name='translit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_app.Hotline'),
        ),
    ]
