# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0008_hotlineky_translit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesofincoming',
            name='translit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_app.RulesOfIncomingKy'),
        ),
        migrations.AlterField(
            model_name='rulesofincoming',
            name='text_ru',
            field=redactor.fields.RedactorField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
