# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0010_auto_20160709_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqky',
            name='answer_ky',
            field=models.TextField(verbose_name='\u0416\u043e\u043e\u043f'),
        ),
        migrations.AlterField(
            model_name='faqky',
            name='question_ky',
            field=models.TextField(verbose_name='\u0421\u0443\u0440\u043e\u043e'),
        ),
        migrations.AlterField(
            model_name='rulesofincomingky',
            name='text_ky',
            field=models.TextField(verbose_name='\u0411\u0430\u044f\u043d\u0434\u043e\u043e'),
        ),
        migrations.AlterField(
            model_name='rulesofincomingky',
            name='title_ky',
            field=models.CharField(max_length=1000, verbose_name='\u0410\u0442\u0430\u043b\u044b\u0448'),
        ),
        migrations.AlterField(
            model_name='rulesofmigrationky',
            name='text_ky',
            field=models.TextField(verbose_name='\u0411\u0430\u044f\u043d\u0434\u043e\u043e'),
        ),
        migrations.AlterField(
            model_name='rulesofmigrationky',
            name='title_ky',
            field=models.CharField(max_length=1000, verbose_name='\u0410\u0442\u0430\u043b\u044b\u0448'),
        ),
    ]
