# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 08:11
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0012_auto_20160711_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesofincomingky',
            name='text_ky',
            field=redactor.fields.RedactorField(verbose_name='\u0411\u0430\u044f\u043d\u0434\u043e\u043e'),
        ),
        migrations.AlterField(
            model_name='rulesofmigration',
            name='text_ru',
            field=redactor.fields.RedactorField(verbose_name='\u0411\u0430\u044f\u043d\u0434\u043e\u043e'),
        ),
        migrations.AlterField(
            model_name='rulesofmigrationky',
            name='text_ky',
            field=redactor.fields.RedactorField(verbose_name='\u0411\u0430\u044f\u043d\u0434\u043e\u043e'),
        ),
    ]
