# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=1000)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Embassy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('site', models.URLField(blank=True, default='\u0441\u0430\u0439\u0442\u0430 \u043d\u0435\u0442', null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='consulate',
            name='embassy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point.Embassy'),
        ),
    ]
