# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embassy',
            options={'verbose_name': '\u043f\u043e\u0441\u043e\u043b\u044c\u0441\u0442\u0432\u043e', 'verbose_name_plural': '\u041f\u043e\u0441\u043e\u043b\u044c\u0441\u0442\u0432\u0430'},
        ),
        migrations.AlterField(
            model_name='consulate',
            name='address',
            field=models.TextField(verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='consulate',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='consulate',
            name='region',
            field=models.CharField(max_length=1000, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='embassy',
            name='address',
            field=models.TextField(verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='embassy',
            name='country',
            field=models.CharField(max_length=100, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='embassy',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0430\u044f \u043f\u043e\u0447\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='embassy',
            name='fax',
            field=models.CharField(max_length=100, verbose_name='\u0424\u0430\u043a\u0441'),
        ),
        migrations.AlterField(
            model_name='embassy',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='embassy',
            name='site',
            field=models.CharField(blank=True, default='\u0441\u0430\u0439\u0442\u0430 \u043d\u0435\u0442', max_length=100, null=True, verbose_name='\u0421\u0430\u0439\u0442'),
        ),
    ]
