# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_auto_20160707_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulate',
            options={'verbose_name': '\u043e\u0431\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u044b\u0439 \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044c', 'verbose_name_plural': '\u041e\u0431\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u044b\u0435 \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u0438'},
        ),
    ]
